<<<<<<< HEAD
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
    batch: "true"
    branches:
      include:
        - develop
        - master
    paths:
      exclude:
        - README.md
        - azure-pipelines.yml
  pr:
    autoCancel: "true"
    branches:
      include:
        - develop
        - master
    paths:
      exclude:
        - README.md
jobs:
#Deploy master to SIT
- job: DEVDeploy
condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
steps:
    - task: NodeTool@0
    inputs:
=======
trigger:
  batch: "true"
  branches:
    include:
      - develop
      - master
  paths:
    exclude:
      - README.md
      - azure-pipelines.yml
pr:
  autoCancel: "true"
  branches:
    include:
      - develop
      - master
  paths:
    exclude:
      - README.md
jobs:
#Deploy develop to DEV
- job: DEVDeploy
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
  steps:
    - task: NodeTool@0
      inputs:
>>>>>>> fb34da38073f6df503cd46da8437397852d08caf
        versionSpec: '>=14.6.0'
        checkLatest: true
    - bash: 
        npm install sfdx-cli --global
<<<<<<< HEAD
    displayName: Install Salesforce CLI
    - bash: 
        sfdx plugins:install sfdx-git-delta
    displayName: Install Salesforce Git Delta
    - bash: 
        sfdx sgd:source:delta --to HEAD --from HEAD^ --output .
    displayName: Get Commit Delta Components
    - bash: 
        sfdx plugins:install @salesforce/sfdx-scanner
    displayName: Install cli scanner     
    - bash: 
        # sfdx force:auth:jwt:grant --clientid $(ClientId) --jwtkeyfile assets/server.key --username $(Username) --setdefaultdevhubusername -a my-hub-org
        sfdx force:auth:jwt:grant --clientid $(salesforceDevOrgClientId) --jwtkeyfile ./build/server.key --username $(salesforceDevOrgUserName) --instanceurl $(salesforceDevOrgInstanceURL) -a devOrg
    displayName: Authorize salesforce org
    # we need to convert the source into mdapi format to run the pmd scanner on the converted files 
    - bash: 
        sfdx force:source:convert --manifest=package/package.xml  --outputdir=convert
    displayName: Convert to deploy source

    - bash: 
        sfdx scanner:run --target=convert --format=json --outfile= . --normalize-severity --category "Security,Design,Best Practices"
    displayName: Run PMD Scanner       
    - bash:     
        sfdx force:mdapi:deploy -l RunLocalTests -d convert -u $(salesforceDevOrgUserName) -w 10
    displayName: Deploy source code
    - bash: 
        sfdx force:mdapi:deploy:report --verbose
    displayName: display results
=======
      displayName: Install Salesforce CLI
    - bash: 
        echo 'y' | sfdx plugins:install sfdx-git-delta
      displayName: Install Salesforce Git Delta
    - bash: 
        sfdx sgd:source:delta --to HEAD --from HEAD^ --output .
      displayName: Get Commit Delta Components
    - bash: 
        sfdx plugins:install @salesforce/sfdx-scanner
      displayName: Install Cli scanner     
    - bash: 
        sfdx force:auth:jwt:grant --clientid $(salesforceDevOrgClientId) --jwtkeyfile ./build/server.key --username $(salesforceDevOrgUserName) --instanceurl $(salesforceDevOrgInstanceURL) -a devOrg
      displayName: Authorize salesforce org
    - bash: #cahnged output directory to src
        sfdx force:source:convert --manifest=package/package.xml  --outputdir=src
      displayName: Convert to deploy source
    - bash:
       mkdir pmdScanner 
      displayName: create folder for storing PMD scanner results
    - bash: 
        sfdx scanner:run --target src --format junit --outputfile=pmdScanner --normalize-severity --category "Security,Design,Best Practices" --severity-threshold=1
      displayName: Run PMD Scanner
    - bash: 
        sfdx force:mdapi:deploy -l RunLocalTests -d src -u $(salesforceDevOrgUserName) -w 10
      displayName: Deploy source code
    - bash: 
        sfdx force:mdapi:deploy:report --verbose -u $(salesforceDevOrgUserName)
      displayName: Report on source code deployment      
>>>>>>> fb34da38073f6df503cd46da8437397852d08caf
